### ISSUE TITLE
backslash error

### ISSUE THREAD

**Issue by stardiviner** [benma/visual-regexp.el#23]
I got this error when I input `\` in `vr/isearch-forward`

#+BEGIN_EXAMPLE
(invalid-regexp "Trailing backslash")
  re-search-forward("\\" 387940 t)
  isearch-lazy-highlight-search()
  isearch-lazy-highlight-update()
  apply(isearch-lazy-highlight-update nil)
  timer-event-handler([t 0 0 250000 nil isearch-lazy-highlight-update nil idle 0])
  recursive-edit()
#+END_EXAMPLE

And the ~\~ in isearch input is:

#+BEGIN_EXAMPLE
\ runs the command isearch-printing-char (found in
overriding-terminal-local-map), which is an interactive compiled Lisp function.

(isearch-printing-char &optional CHAR COUNT)

Add this ordinary printing CHAR to the search string and search.
With argument, add COUNT copies of the character.
#+END_EXAMPLE

**Comment by benma** [comment]
Thanks. Unfortunately, I cannot reproduce the issue, am I doing it wrong?

Python engine:
![](http://i.imgur.com/5FMrbeA.png).

Emacs engine:
![](http://i.imgur.com/FehyVUf.png)

If your problem persists, please reopen the issue in [visual-regexp-steroids](https://github.com/benma/visual-regexp-steroids.el), as the `vr/isearch-forward` function lives there.

**Comment by stardiviner** [comment]
https://github.com/benma/visual-regexp-steroids.el/issues/9
