### ISSUE TITLE
Add enhanced query-replace history like in emacs 25.0 [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [benma/visual-regexp.el#24]
Hi,

Can you please add the enhanced query-replace history like the one added in emacs 25.0 for the `M-x query-replace`?

From the `NEWS` file:
> ** Search and Replace
> 
> *** Query-replace history is enhanced.
> When query-replace reads the FROM string from the minibuffer, typing
> `M-p` will now show previous replacements as "FROM SEP TO", where FROM
> and TO are the original text and its replacement, and SEP is an arrow
> string defined by the new variable `query-replace-from-to-separator`.
> To select a prior replacement, type `M-p` until the desired
> replacement appears in the minibuffer, and then exit the minibuffer by
> typing RET.

[Brief description of this feature](http://endlessparentheses.com/new-in-emacs-25-1-query-replace-history-is-enhanced-.html)

**Comment by benma** [comment]
Sorry for the slight delay :sweat_smile: 

I pushed some code to make this happen in 80668e93223ad54d0c4c8facc1bac1cdf2155f4c. Please give feedback and report any bugs you might find.

**Comment by kaushalmodi** [comment]
No worries, thanks for implementing this! :)
