### ISSUE TITLE
Provide an equivalent of isearch-query-replace-regexp

### ISSUE THREAD

**Issue by cpitclaudel** [benma/visual-regexp.el#25]
In isearch mode, typing <kbd>C-M-%</kbd> launches `isearch-query-replace-regexp`, which in turn calls `query-replace-regexp` with the current search as the regexp search string. 

Is there a simple way to achieve similar behaviour using vr? Ideally something like:

```
(require 'visual-regexp-steroids)
(define-key isearch-mode-map (kbd "C-M-%") 'vr/isearch-query-replace)
```

**Comment by benma** [comment]
I don't know of a very simple way. Seems as if you have to copy the [isearch-query-replace](https://github.com/emacs-mirror/emacs/blob/master/lisp/isearch.el#L1690) function, replace the `(perform-replace ...)` part with something that calls `vr/query-replace` (or `vr/replace`), but with the regexp string already set. This functionality is not there and would probably require modifications to `vr--interactive-get-args`.

I do wonder why `isearch-query-replace` needs to be so long, seems like that could have been made a lot simpler.
