### ISSUE TITLE
Newline '\n' in Replace

### ISSUE THREAD

**Issue by JP-Ellis** [benma/visual-regexp.el#28]
I am not sure whether this issue is specific to this or [visual-regexp-steroids](https://github.com/benma/visual-regexp-steroids.el), but I'll report the issue here.

When the replacement string contains an `\n`, it inserts a newline regardless of any escape sequence.  I have illustrated below a few examples of what the replacement text produces.

This works as expected:
```
abc\ndef
---▼---
abc
def
```

But this does not:
```
abc\\ndef
---▼---
abc\
def
```
One would expect the replacement to be `abc\ndef` without any newlines.

**Comment by benma** [comment]
Thanks for the report. It was an issue in the steroids package. This commit should fix it:

https://github.com/benma/visual-regexp-steroids.el/commit/2a50710dea5be872b31ea56f74b4cd57d6e61461

Please let me know if the issue is solved for you.

**Comment by JP-Ellis** [comment]
This has fixed the issue; thanks for that!
