### ISSUE TITLE
Make visual-regexp available on MELPA stable

### ISSUE THREAD

**Issue by gdv** [benma/visual-regexp.el#40]
Thanks for your great package!

[Melpa stable](https://stable.melpa.org/) accepts only stable versions of packages (while MELPA takes the latest commit of each package). So visual-regexp is not available via Melpa stable.
To make it happen, you should tag the latest commit vith a [semver](http://www.semver.org) version.
For example, giving the following commands should suffice:
```
git tag v1.0.1 2cf4dc5a2dff0736eb2e2da95997d7274bbb5766
git push
```

Since tagging cannot be done via a pull request, I cannot help you more.
Thanks!

**Comment by benma** [comment]
I am not a user of Melpa stable, so please quickly help me understand it: how/when do people usually upgrade packages from stable? How is it different from using normal melpa but not upgrading the package as soon as an upgrade is available?

The way I commit to this repo, I'd create a new tag for almost every commit. Does that still make sense?

**Comment by gdv** [comment]
From a user point of view, upgrading a package from stable or from standard melpa is the same.
A new version appears in melpa stable when a commit is tagged.

I do understand that if you plan to have an always-working master branch, tagging each version is a nuisance, but from a user (me) point of view, it would make sense. You can add something like [https://github.com/fmahnke/shell-semver](https://github.com/fmahnke/shell-semver) to your post-commit hooks, if you want to automate the release.

OTOH, if you have more confidence is some of your commits, then you could tag only those.
Or you can go with a time-based release. Let's say once a month you tag a commit.
Anyone of these possibilities would be fine.

I just would like melpa stable users to see (and use) your packages.

Thanks

**Comment by benma** [comment]
Sorry for the delay!

I now tagged the current master branch with v1.0.0 (and the same for the steroids package). Let's see if that worked.

**Comment by benma** [comment]
It's on melpa stable now: http://stable.melpa.org/#/visual-regexp

**Comment by gdv** [comment]
Wonderful!
Thanks again.
