### ISSUE TITLE
wrong-type-argument markerp nil

### ISSUE THREAD

**Issue by CyberShadow** [benma/visual-regexp.el#43]
* GNU Emacs 25.1.1
* visual-regexp df7812007fb9836b290c4528ebddfc9d146b2fb6

```
echo -n '"' > a
emacs -Q -l visual-regexp.el a
M-x vr/replace
"\(a\)?\(\)
RET
RET
Home
M-x vr/replace
Up
```

Step 4 is including the leading double quote.

BTW, at step 5 it shows "1 matches" but after step 6 it shows "replaced 0 matches".

**Comment by benma** [comment]
Thanks for the report. I pushed a fix, please let me know if it works.

Out of curiosity: how did you come up with the trailing empty group? I can't think of a practical use. Without it, the error did not occur.

**Comment by CyberShadow** [comment]
> I pushed a fix, please let me know if it works.

It does, thanks!

> Out of curiosity: how did you come up with the trailing empty group? I can't think of a practical use. Without it, the error did not occur.

I reduced the regular expression from a more complex one: `	"\(if \(.*\)?, \)?\(.*?\) `. I've confirmed that the fix works with the longer expression as well.
