### ISSUE TITLE
support thing-at-point

### ISSUE THREAD

**Issue by yuandaxing** [benma/visual-regexp.el#44]
I use vr/query-replace a lot.
often i like to grab the word at the my cursor to the replace mini-buffer.
I think thing-at-the point is a great feature.

could you please support that?

**Comment by benma** [comment]
Hi

You can add something like this to your config:

```elisp
(defvar vr-current-thing-at-point)
(defun vr-thing-at-point-minibuffer-setup ()
  (when (and vr-current-thing-at-point
             (equal vr--in-minibuffer 'vr--minibuffer-regexp))
    (insert vr-current-thing-at-point)))
(add-hook 'minibuffer-setup-hook 'vr-thing-at-point-minibuffer-setup)

(defun vr-thing-at-point ()
  (interactive)
  (let ((vr-current-thing-at-point (thing-at-point 'symbol t)))
    (call-interactively 'vr/replace)))
```

You can tweak it to match your needs better (i.e. how `thing-at-point` is invoked).

Does this help?

**Comment by yuandaxing** [comment]
yes, it works.
the bad thing is that, 
it give me the error message "vr-current-thing-at-point" is void.

**Comment by benma** [comment]
Change `(defvar vr-current-thing-at-point)` to `(defvar vr-current-thing-at-point nil)`.

**Comment by benma** [comment]
Is it ok now? If so, please close the issue.

**Comment by yuandaxing** [comment]
fixed
